apiVersion: 1

datasources:
  - name: WorldCup Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: worldcup
    user: worldcup
    secureJsonData:
      password: worldcup
    jsonData:
      database: worldcup
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true